version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Apache Tomcat...
      # - wget https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.71/bin/apache-tomcat-9.0.71.zip
      # - unzip apache-tomcat-9.0.71.zip
  build:
    commands:
      - echo Deploying WAR file to Apache Tomcat...
      - mvn clean install
      # - mvn -f pom.xml compile
      # - mvn -f pom.xml package
  post_build:
    commands:
      - echo Build Success
artifacts:
  files:
    - target/*.war
    - scripts/*.sh
    - appspec.yml
  discard-paths: yes
  